#
# Copyright 2026 The OKDP Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: "Parse Hive Metastore Versions"
description: "Reads metastore version list and package.json version"

outputs:
  metastore_versions:
    description: "List of metastore versions extracted from docker/metastore_4x.version"
    value: ${{ steps.read_metastore.outputs.metastore_versions }}

runs:
  using: "composite"
  steps:
    - name: Read metastore versions
      id: read_metastore
      shell: bash
      run: |
        # Extract lines like ARG_METASTORE_VERSION=4.0.1
        versions=$(grep -oP 'ARG_METASTORE_VERSION=\K[0-9.]+' docker/metastore_4x.version | jq -R . | jq -s -c .)

        echo "Parsed metastore versions: $versions"
        echo "metastore_versions=$versions" >> "$GITHUB_OUTPUT"

