
---
apiVersion: batch/v1
kind: Job
metadata:
  name:  {{ include "metastore.jobName" . }}
  namespace: {{ .Release.Namespace  }}
  labels:
    {{- include "metastore.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ttlSecondsAfterFinished: {{ .Values.initJob.ttlSecondsAfterFinished }}
  template:
    metadata:
      labels:
      {{- include "metastore.labels" . | nindent 8 }}
      {{- if .Values.aws.podIamRole }}
      annotations:
        iam.amazonaws.com/role: {{ .Values.aws.podIamRole }}
      {{- end }}
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: metastore
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.containerSecurityContext }}
          securityContext:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: LOG_LEVEL
              value: "{{ .Values.logLevel }}"
            # ----------------------------- DB configuration
            - name: DB_DRIVER_REF
              value: {{ .Values.db.driverRef }}
            - name: DB_DRIVER_NAME
              value: {{ .Values.db.driverName }} 
            - name: DB_HOST
              value: {{ .Values.db.host }}
            - name: DB_PORT
              value: "{{ .Values.db.port | default "5432" }}"
            - name: HIVEMS_DB
              value: {{ .Values.db.databaseName }}
            - name: HIVEMS_USER
              value: {{ .Values.db.user.name }}
            - name: HIVEMS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.user.password.secretName }}
                  key: {{ .Values.db.user.password.propertyName }}
          command: ["/bin/sh","-c"]
          args:
            - |
              TABLE_EXISTS=$(mysql -h $DB_HOST -u$HIVEMS_USER -p$HIVEMS_PASSWORD -D $HIVEMS_DB -sN -e "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = '${HIVEMS_DB}' AND table_name = 'METASTORE_DB_PROPERTIES';")
              echo "TABLE_EXISTS: $TABLE_EXISTS"
              if [ "$TABLE_EXISTS" != "" ] && [ "$TABLE_EXISTS" -eq 0 ]; then
                /metastore.sh init
              fi
      restartPolicy: Never
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
