{{- if.Values.networkPolicies.enabled }}

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "metastore.networkPolicyName" . }}
  namespace:  {{ .Release.Namespace  }}
  labels:
    {{- include "metastore.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  podSelector:
    matchLabels:
      {{- include "metastore.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        {{- with.Values.networkPolicies.allowedNamespaceLabels }}
        - namespaceSelector:
            matchLabels:
              {{- . | nindent 10 }}
        {{- end }}
        {{- with.Values.networkPolicies.allowedNamespace }}
        - namespaceSelector:
            matchExpressions:
              - key: kubernetes.io/metadata.name
                operator: In
                values:
                  {{- . | nindent 12 }}
        {{- end }}
      ports:
        - protocol: TCP
          port: 9083

{{- end }}